version: "3.8"

services:
  frontend:
    build: ./task-manager-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./task-manager-frontend:/app:cached
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - backend

  backend:
    build: ./task-manager-backend
    ports:
      - "5001:5001"
    volumes:
      - ./task-manager-backend:/app
      - /app/node_modules
    env_file:
      - ./task-manager-backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
